"""v0.6.1 — per-stack docker-compose fragment writers.

PURE ADDITIVE MODULE. Same atomic-write + external-network shape as
`airflow_overlay.py`, but with a critical contract difference:

  * Airflow / Dagster / Superset overlays are OPT-IN operational
    extras gated by `LHS_*_ENABLED` env flags. They never run by
    default.
  * Stack compose fragments here are REQUIRED to make the four
    `candidate` stacks installable at all. UDP's upstream
    docker-compose.yml does NOT ship a `nessie`, `polaris`,
    `hive-metastore`, or `postgres-hms` service definition, so each
    of those stacks would fail at the `docker compose up` step.

The runner calls `write_fragment(stack_id, install_dir, env)` from
`_step_env` after `_write_optional_overlays`. The writer returns either
a `Path` (fragment written) or `None` (no fragment needed — the stable
`udp-local-v0.2` stack hits this branch). When a path is returned, the
runner prepends an entry into `self._overlays` so the docker_compose_up
argv injects `-f docker-compose.fragment.yml` BEFORE any opt-in overlays
(so the fragment's services are visible to anything that depends on them).

Each render function returns the YAML body as a string. `write_fragment`
is responsible for writing it atomically to disk. This keeps the render
functions trivially unit-testable without touching the filesystem.

All services attach to the base stack's docker network via an `external:
true` declaration, exactly like `airflow_overlay.py`. Without this they
would land on a second network and couldn't talk to MinIO (or each other)
by service name.

Image tags pinned 2026-05-17 — matched against the manifests in
`stacks/iceberg-nessie-trino-local-v0.1.yaml`,
`stacks/hudi-hms-spark-local-v0.1.yaml`,
`stacks/delta-hms-spark-trino-local-v0.1.yaml`, and
`stacks/iceberg-polaris-spark-local-v0.1.yaml`.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Callable, Optional


log = logging.getLogger("lhs.stack_compose_fragments")


# ---- pinned image tags (verified 2026-05-17 against stack manifests) ----
_NESSIE_IMAGE = "ghcr.io/projectnessie/nessie:0.99.0"
_HMS_IMAGE = "bitsondatadev/hive-metastore:latest"
_POLARIS_IMAGE = "apache/polaris:1.4.1"  # bumped from 1.0.1 — that tag never published; 1.4.1 is real + has CVE fixes (Gemini research 2026-05-17, verified via docker manifest inspect)
_POSTGRES_IMAGE = "postgres:15-alpine"


# Filename the runner injects with `-f` when a fragment is needed.
# Exported so runner.py and tests can import it without parsing.
FRAGMENT_FILENAME = "docker-compose.fragment.yml"


# Service names each fragment adds. The runner appends these to the
# explicit `docker compose up -d <services>` argv so the fragment's
# services come up alongside the base stack's services rather than
# being filtered out by the runner's per-cart service list.
FRAGMENT_SERVICES: dict[str, list[str]] = {
    "iceberg-nessie-trino-local-v0.1":  ["nessie"],
    "hudi-hms-spark-local-v0.1":        ["postgres-hms", "hive-metastore"],
    "delta-hms-spark-trino-local-v0.1": ["postgres-hms", "hive-metastore"],
    "iceberg-polaris-spark-local-v0.1": ["postgres-polaris", "polaris"],
}


# Named volumes for postgres data, kept distinct per stack so `docker
# volume rm` is targeted and side-by-side installs don't clobber each
# other. Idempotent — re-running docker compose up reuses the volume.
_PG_HMS_VOLUME = "udp-postgres-hms-data"
_PG_POLARIS_VOLUME = "udp-postgres-polaris-data"


# ---------- helpers ----------


def _atomic_write(path: Path, data: str) -> None:
    """tmp + os.replace atomic write. Same pattern as airflow_overlay.py
    — avoids half-written files on Ctrl-C or power loss."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(data, encoding="utf-8")
    os.replace(tmp, path)


def _network_name(install_dir: Path, env: dict) -> str:
    """Resolve the docker network name to attach to. The base stack lives
    on `<install_dir.name>_default` by docker compose convention; the env
    can override via LHS_DOCKER_NETWORK if the operator renamed it."""
    explicit = (env.get("LHS_DOCKER_NETWORK") or "").strip()
    if explicit:
        return explicit
    return f"{install_dir.name}_default"


# ---------- render functions ----------


def _render_nessie_fragment(env: dict) -> str:
    """Render the Nessie fragment.

    Single service: `nessie` on port 19120, in-memory version store for
    the pilot (no persistent volume — restart wipes branches/commits,
    which is fine for v0.1 candidate scope). OIDC explicitly disabled
    so the catalog accepts anonymous Iceberg REST calls from Spark /
    Trino / StarRocks without token plumbing in the bootstrap script.
    """
    return (
        "# docker-compose.fragment.yml -- Nessie service for "
        "iceberg-nessie-trino-local-v0.1.\n"
        "# Generated by backend/stack_compose_fragments.py.\n"
        "#\n"
        "# REQUIRED: UDP's upstream docker-compose.yml does not ship a\n"
        "# Nessie service. This fragment supplies it so `docker compose\n"
        "# up` for this stack actually has a catalog to bring up.\n"
        "services:\n"
        "  nessie:\n"
        f"    image: {_NESSIE_IMAGE}\n"
        "    container_name: udp-nessie\n"
        "    restart: unless-stopped\n"
        "    environment:\n"
        "      # IN_MEMORY is the pilot-scope default. Swap to JDBC and\n"
        "      # add a postgres-nessie service when promoting past v0.1.\n"
        "      NESSIE_VERSION_STORE_TYPE: IN_MEMORY\n"
        "      QUARKUS_OIDC_TENANT_ENABLED: \"false\"\n"
        "    ports:\n"
        "      - \"19120:19120\"\n"
        "    healthcheck:\n"
        "      test: [\"CMD\", \"curl\", \"-fsS\", \"http://localhost:19120/q/health\"]\n"
        "      interval: 10s\n"
        "      timeout: 5s\n"
        "      retries: 12\n"
        "    networks:\n"
        "      - default\n"
        "networks:\n"
        "  default:\n"
        f"    name: {_network_name_token(env)}\n"
        "    external: true\n"
    )


def _render_hms_fragment(env: dict) -> str:
    """Render the Hive Metastore fragment.

    Two services: `postgres-hms` (backing DB) and `hive-metastore`
    (Thrift on 9083). The bitsondatadev image expects DATABASE_HOST /
    DATABASE_DB / DATABASE_USER / DATABASE_PASSWORD env vars at boot
    so it can render metastore-site.xml. depends_on uses
    service_healthy so HMS doesn't try to connect to Postgres before
    pg_isready returns 0.
    """
    return (
        "# docker-compose.fragment.yml -- Hive Metastore + Postgres for\n"
        "# hudi-hms-spark-local-v0.1 / delta-hms-spark-trino-local-v0.1.\n"
        "# Generated by backend/stack_compose_fragments.py.\n"
        "#\n"
        "# REQUIRED: UDP's upstream docker-compose.yml does not ship\n"
        "# hive-metastore + postgres-hms. This fragment supplies both\n"
        "# so the HMS-backed stacks actually have a catalog to bring up.\n"
        "services:\n"
        "  postgres-hms:\n"
        f"    image: {_POSTGRES_IMAGE}\n"
        "    container_name: udp-postgres-hms\n"
        "    restart: unless-stopped\n"
        "    environment:\n"
        "      POSTGRES_USER: hive\n"
        "      POSTGRES_PASSWORD: ${HMS_DB_PASSWORD:-hive_password_pilot}\n"
        "      POSTGRES_DB: metastore\n"
        "    volumes:\n"
        f"      - {_PG_HMS_VOLUME}:/var/lib/postgresql/data\n"
        "    ports:\n"
        "      - \"5432:5432\"\n"
        "    healthcheck:\n"
        "      test: [\"CMD\", \"pg_isready\", \"-U\", \"hive\", \"-d\", \"metastore\"]\n"
        "      interval: 10s\n"
        "      timeout: 5s\n"
        "      retries: 10\n"
        "    networks:\n"
        "      - default\n"
        "  hive-metastore:\n"
        f"    image: {_HMS_IMAGE}\n"
        "    container_name: udp-hive-metastore\n"
        "    restart: unless-stopped\n"
        "    depends_on:\n"
        "      postgres-hms:\n"
        "        condition: service_healthy\n"
        "    environment:\n"
        "      # bitsondatadev/hive-metastore reads DATABASE_* + HIVE_*\n"
        "      # env vars to render metastore-site.xml at boot.\n"
        "      HIVE_METASTORE_DB_TYPE: postgres\n"
        "      DATABASE_HOST: postgres-hms\n"
        "      DATABASE_DB: metastore\n"
        "      DATABASE_USER: hive\n"
        "      DATABASE_PASSWORD: ${HMS_DB_PASSWORD:-hive_password_pilot}\n"
        "    ports:\n"
        "      - \"9083:9083\"\n"
        "    healthcheck:\n"
        "      # Cheap TCP probe — the HMS image has no curl/wget, and\n"
        "      # the Thrift protocol doesn't speak HTTP. nc -z confirms\n"
        "      # the listener is accepting connections.\n"
        "      test: [\"CMD-SHELL\", \"nc -z localhost 9083 || exit 1\"]\n"
        "      interval: 15s\n"
        "      timeout: 5s\n"
        "      retries: 10\n"
        "    networks:\n"
        "      - default\n"
        "volumes:\n"
        f"  {_PG_HMS_VOLUME}:\n"
        "networks:\n"
        "  default:\n"
        f"    name: {_network_name_token(env)}\n"
        "    external: true\n"
    )


def _render_polaris_fragment(env: dict) -> str:
    """Render the Polaris fragment.

    Two services: `postgres-polaris` (JDBC persistence backing store)
    and `polaris` (catalog REST on 8181 + management API on 8182).
    Host port 5433 for the Postgres so it doesn't conflict with HMS
    Postgres on 5432 if an operator ever runs both stacks side-by-side.
    Inside the docker network both are still on 5432 (the container
    port is unchanged), so polaris's JDBC URL points at port 5432.
    """
    return (
        "# docker-compose.fragment.yml -- Polaris + backing Postgres for\n"
        "# iceberg-polaris-spark-local-v0.1.\n"
        "# Generated by backend/stack_compose_fragments.py.\n"
        "#\n"
        "# REQUIRED: UDP's upstream docker-compose.yml does not ship\n"
        "# Polaris or its backing Postgres. This fragment supplies both\n"
        "# so the Polaris-backed stack actually has a catalog to bring up.\n"
        "#\n"
        "# Host port 5433 for the Postgres — 5432 may be held by the HMS\n"
        "# Postgres if an operator runs both stacks on the same host. The\n"
        "# CONTAINER side stays on 5432, so polaris's JDBC URL uses 5432.\n"
        "services:\n"
        "  postgres-polaris:\n"
        f"    image: {_POSTGRES_IMAGE}\n"
        "    container_name: udp-postgres-polaris\n"
        "    restart: unless-stopped\n"
        "    environment:\n"
        "      POSTGRES_USER: polaris\n"
        "      POSTGRES_PASSWORD: ${POLARIS_DB_PASSWORD:-polaris_password_pilot}\n"
        "      POSTGRES_DB: polaris\n"
        "    volumes:\n"
        f"      - {_PG_POLARIS_VOLUME}:/var/lib/postgresql/data\n"
        "    ports:\n"
        "      - \"5433:5432\"\n"
        "    healthcheck:\n"
        "      test: [\"CMD\", \"pg_isready\", \"-U\", \"polaris\", \"-d\", \"polaris\"]\n"
        "      interval: 10s\n"
        "      timeout: 5s\n"
        "      retries: 10\n"
        "    networks:\n"
        "      - default\n"
        "  polaris:\n"
        f"    image: {_POLARIS_IMAGE}\n"
        "    container_name: udp-polaris\n"
        "    restart: unless-stopped\n"
        "    depends_on:\n"
        "      postgres-polaris:\n"
        "        condition: service_healthy\n"
        "    environment:\n"
        "      POLARIS_PERSISTENCE_TYPE: jdbc\n"
        "      POLARIS_PERSISTENCE_JDBC_URL: jdbc:postgresql://postgres-polaris:5432/polaris\n"
        "      POLARIS_PERSISTENCE_JDBC_USER: polaris\n"
        "      POLARIS_PERSISTENCE_JDBC_PASSWORD: ${POLARIS_DB_PASSWORD:-polaris_password_pilot}\n"
        "    ports:\n"
        "      - \"8181:8181\"\n"
        "      - \"8182:8182\"\n"
        "    healthcheck:\n"
        "      test: [\"CMD\", \"curl\", \"-fsS\", \"http://localhost:8182/q/health\"]\n"
        "      interval: 15s\n"
        "      timeout: 5s\n"
        "      retries: 12\n"
        "    networks:\n"
        "      - default\n"
        "volumes:\n"
        f"  {_PG_POLARIS_VOLUME}:\n"
        "networks:\n"
        "  default:\n"
        f"    name: {_network_name_token(env)}\n"
        "    external: true\n"
    )


def _network_name_token(env: dict) -> str:
    """Resolve the docker network name from the env dict alone.

    Mirrors `_network_name` but without an install_dir — we can't always
    know it at render time (tests render directly). When the env carries
    `LHS_DOCKER_NETWORK`, honor it; otherwise default to `udp_default`,
    which docker compose auto-creates for a directory literally named
    `udp`. The runner's call path passes the real network name in via
    env when needed; tests rely on the default.
    """
    explicit = (env.get("LHS_DOCKER_NETWORK") or "").strip()
    if explicit:
        return explicit
    return env.get("LHS_BASE_NETWORK_NAME") or "udp_default"


# ---------- dispatch ----------


_FRAGMENT_RENDERERS: dict[str, Callable[[dict], str]] = {
    "iceberg-nessie-trino-local-v0.1":  _render_nessie_fragment,
    "hudi-hms-spark-local-v0.1":        _render_hms_fragment,
    "delta-hms-spark-trino-local-v0.1": _render_hms_fragment,
    "iceberg-polaris-spark-local-v0.1": _render_polaris_fragment,
}


# ---------- public API ----------


def write_fragment(stack_id: str, install_dir: Path,
                   env: dict[str, str]) -> Optional[Path]:
    """Write the per-stack compose fragment into install_dir.

    Returns the Path to the written `docker-compose.fragment.yml`, or
    `None` if the given `stack_id` has no fragment registered (the
    stable `udp-local-v0.2` stack hits this branch — UDP's upstream
    compose already has every service it needs).

    Idempotent — re-running with the same install_dir overwrites the
    file atomically. Safe to call from `runner._step_env` every install.

    The env dict is the merged install env (manifest defaults + user
    overrides). We pass it through to the renderer so the network name
    can be honored via `LHS_DOCKER_NETWORK` / `LHS_BASE_NETWORK_NAME`.
    For the install path, the renderer's `_network_name_token` default
    of `udp_default` is then OVERRIDDEN by the per-install network the
    runner injects through env.
    """
    renderer = _FRAGMENT_RENDERERS.get(stack_id)
    if renderer is None:
        log.debug("no fragment renderer for stack_id=%r", stack_id)
        return None

    # If the env doesn't already carry an explicit network name, fall
    # back to the install_dir-derived default so the fragment attaches
    # to the right network for THIS install rather than a generic one.
    enriched = dict(env or {})
    if not (enriched.get("LHS_DOCKER_NETWORK") or "").strip():
        enriched["LHS_BASE_NETWORK_NAME"] = _network_name(install_dir, enriched)

    body = renderer(enriched)
    path = install_dir / FRAGMENT_FILENAME
    _atomic_write(path, body)
    log.info(
        "stack compose fragment written stack_id=%s install_dir=%s",
        stack_id, install_dir,
    )
    return path
